// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-31yLdR9z2AzHV168puGCF-KSaMtMnk',
    appId: '1:793858168053:web:452d464f42e77b1aba21bc',
    messagingSenderId: '793858168053',
    projectId: 'society1-93b11',
    authDomain: 'society1-93b11.firebaseapp.com',
    storageBucket: 'society1-93b11.appspot.com',
    measurementId: 'G-ER4HK0ZFC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqNU8kZ3NsctZePGxGZJSl_pyqH0KzdI',
    appId: '1:793858168053:android:c005a14729545664ba21bc',
    messagingSenderId: '793858168053',
    projectId: 'society1-93b11',
    storageBucket: 'society1-93b11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTUNm9z_AYhQcsH7hgZC9LXDxa5VvGV0',
    appId: '1:793858168053:ios:6e708ac14473abffba21bc',
    messagingSenderId: '793858168053',
    projectId: 'society1-93b11',
    storageBucket: 'society1-93b11.appspot.com',
    iosBundleId: 'com.example.secureSociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyTUNm9z_AYhQcsH7hgZC9LXDxa5VvGV0',
    appId: '1:793858168053:ios:474dc75261286402ba21bc',
    messagingSenderId: '793858168053',
    projectId: 'society1-93b11',
    storageBucket: 'society1-93b11.appspot.com',
    iosBundleId: 'com.example.secureSociety.RunnerTests',
  );
}
